//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

   
    public partial class OpBom 
    {
        [MaxLength(40),Required]
        public string ITEMCODE { get; set; }
        [MaxLength(40), Required]
        public string OBCODE { get; set; }
        [MaxLength(40), Required]
        public string OPBOMVER { get; set; }
        [MaxLength(40)]
        public string OBROUTE { get; set; }
        [MaxLength(100)]
        public string OPDESC { get; set; }
        [MaxLength(40), Required]

        public string MUSER { get; set; }
        [Required]
        public int MDATE { get; set; }
        [Required]
        public int MTIME { get; set; }
        [MaxLength(40)]

        public string EATTRIBUTE1 { get; set; }
        [Required]
        public short AVIALABLE { get; set; }
        [MaxLength(22), Required]
        public string ORGID { get; set; }
    }
}
