//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table("TBLMINNO")]
    public partial class MinNo
    {
        [MaxLength(40),Required]
        public string INNO { get; set; }
        [Required]
        public int SEQ { get; set; }
        [MaxLength(40)]

        public string MOBSITEMCODE { get; set; }
        [MaxLength(40)]

        public string MITEMCODE { get; set; }
        [MaxLength(40), Required]

        public string MOCODE { get; set; }
        [MaxLength(40)]

        public string ITEMCODE { get; set; }
        [MaxLength(40), Required]

        public string OPBOMCODE { get; set; }
        [MaxLength(40), Required]

        public string OPBOMVER { get; set; }
        [MaxLength(40), Required]

        public string ROUTECODE { get; set; }
        [MaxLength(40), Required]

        public string OPCODE { get; set; }
        [MaxLength(40), Required]

        public string RESCODE { get; set; }
        [MaxLength(40), Required]

        public string ISTRY { get; set; }
        [MaxLength(40)]

        public string TRYITEMCODE { get; set; }
        [MaxLength(40)]

        public string LOTNO { get; set; }
        [MaxLength(100)]

        public string PCBA { get; set; }
        [MaxLength(100)]

        public string BIOS { get; set; }
        [MaxLength(100)]

        public string VERSION { get; set; }
        [MaxLength(100)]

        public string VENDORITEMCODE { get; set; }
        [MaxLength(100)]

        public string VENDORCODE { get; set; }
        [MaxLength(100)]

        public string DATECODE { get; set; }
        [Required]
        public int QTY { get; set; }
        [MaxLength(1),Required]

        public string ISLAST { get; set; }
        [MaxLength(40), Required]

        public string MUSER { get; set; }
        [Required]
        public int MDATE { get; set; }
        [Required]
        public int MTIME { get; set; }
        [MaxLength(40)]

        public string EATTRIBUTE1 { get; set; }
        [MaxLength(80)]

        public string MITEMNAME { get; set; }
        [MaxLength(40),Required]

        public string MITEMPACKEDNO { get; set; }
        [Required]
        public int PREPAREQTY { get; set; }
        [MaxLength(40)]
        public string GROUPCODE { get; set; }
        [MaxLength(40)]

        public string BINVALUE { get; set; }
    }
}
