//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table("TBLPALLET")]
    public partial class Pallet
    {
        [Key,MaxLength(40)]
        public string PALLETCODE { get; set; }
        [Required]
        public int RCARDCOUNT { get; set; }
        public Nullable<int> CAPACITY { get; set; }
        [MaxLength(40),Required]
        public string MOCODE { get; set; }
        [MaxLength(40), Required]

        public string SSCODE { get; set; }
        [MaxLength(40), Required]

        public string ITEMCODE { get; set; }
        [MaxLength(40), Required]

        public string MUSER { get; set; }
        public Nullable<int> MDATE { get; set; }
        public Nullable<int> MTIME { get; set; }
        [MaxLength(40), Required]

        public string EATTRIBUTE1 { get; set; }
        [MaxLength(22),Required]
        public string ORGID { get; set; }
        [MaxLength(40), Required]

        public string RESCODE { get; set; }
        [MaxLength(40)]
        public string OQCSTATUS { get; set; }
        [MaxLength(40)]

        public string OQCUSER { get; set; }
        public Nullable<int> OQCDATE { get; set; }
        public Nullable<int> OQCTIME { get; set; }
        [MaxLength(40),Required]
        
        public string ITEMGRADE { get; set; }
        public Nullable<int> CARTONCOUNT { get; set; }
        [MaxLength(40)]

        public string ISCM { get; set; }
        [MaxLength(40)]

        public string ONCKDSHELF { get; set; }
    }
}
