//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table("TBLPALLET2RCARDLOG")]
    public partial class Pallet2RcardLog
    {
        public int ID { get; set; }
        [MaxLength(40),Required]
        public string PALLETCODE { get; set; }
        [MaxLength(40), Required]

        public string RCARD { get; set; }
        [MaxLength(40)]

        public string PACKUSER { get; set; }
        public Nullable<int> PACKDATE { get; set; }
        public Nullable<int> PACKTIME { get; set; }
        [MaxLength(40)]

        public string REMOVEUSER { get; set; }
        public Nullable<int> REMOVDATE { get; set; }
        public Nullable<int> REMOVTIME { get; set; }
    }
}
