//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18408
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnitTestForm.Service.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UnitTestForm.Service.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string FrmLogin_Login_LoginSuccess {
            get {
                return ResourceManager.GetString("FrmLogin_Login_LoginSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string FrmLogin_Login_PasswordError {
            get {
                return ResourceManager.GetString("FrmLogin_Login_PasswordError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string FrmLogin_Login_UserNotExist {
            get {
                return ResourceManager.GetString("FrmLogin_Login_UserNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string FrmLogin_Login_UserNotRes {
            get {
                return ResourceManager.GetString("FrmLogin_Login_UserNotRes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string String_FrmGoodNGService_CheckSuccess {
            get {
                return ResourceManager.GetString("String_FrmGoodNGService_CheckSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string String_FrmGoodNGService_CollectSuccess {
            get {
                return ResourceManager.GetString("String_FrmGoodNGService_CollectSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string String_FrmGoodNGService_LotNotOp {
            get {
                return ResourceManager.GetString("String_FrmGoodNGService_LotNotOp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string String_FrmGoodNGService_MoCanNotNull {
            get {
                return ResourceManager.GetString("String_FrmGoodNGService_MoCanNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string String_FrmGoodNGService_MoDontHaveRoute {
            get {
                return ResourceManager.GetString("String_FrmGoodNGService_MoDontHaveRoute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string String_FrmGoodNGService_MoEnough {
            get {
                return ResourceManager.GetString("String_FrmGoodNGService_MoEnough", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string String_FrmGoodNGService_MoNotExit {
            get {
                return ResourceManager.GetString("String_FrmGoodNGService_MoNotExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string String_FrmGoodNGService_MoStatusError {
            get {
                return ResourceManager.GetString("String_FrmGoodNGService_MoStatusError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string String_FrmGoodNGService_NextOp {
            get {
                return ResourceManager.GetString("String_FrmGoodNGService_NextOp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string String_FrmGoodNGService_NowOp {
            get {
                return ResourceManager.GetString("String_FrmGoodNGService_NowOp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string String_FrmGoodNGService_ResNotFirst {
            get {
                return ResourceManager.GetString("String_FrmGoodNGService_ResNotFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string String_FrmGoodNGService_ResNotOp {
            get {
                return ResourceManager.GetString("String_FrmGoodNGService_ResNotOp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string String_FrmGoodNGService_SnHadFinish {
            get {
                return ResourceManager.GetString("String_FrmGoodNGService_SnHadFinish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string String_FrmGoodNGService_SnHadInMo {
            get {
                return ResourceManager.GetString("String_FrmGoodNGService_SnHadInMo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string String_FrmGoodNGService_SnHadNotInMo {
            get {
                return ResourceManager.GetString("String_FrmGoodNGService_SnHadNotInMo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string String_FrmGoodNGService_SnIsRunning {
            get {
                return ResourceManager.GetString("String_FrmGoodNGService_SnIsRunning", resourceCulture);
            }
        }
    }
}
