//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table("TBLFROZEN")]
    public partial class Frozen
    {
        [MaxLength(40),Required]
        public string RCARD { get; set; }
        [MaxLength(40), Required]

        public string LOTNO { get; set; }
        [Required]
        public int LOTSEQ { get; set; }
        [MaxLength(40), Required]

        public string MOCODE { get; set; }
        [MaxLength(40), Required]

        public string MODELCODE { get; set; }
        [MaxLength(40), Required]

        public string ITEMCODE { get; set; }
        [Required]
        public int FROZENSEQ { get; set; }
        [MaxLength(40), Required]

        public string FROZENSTATUS { get; set; }
        [MaxLength(100)]

        public string FROZENREASON { get; set; }
        public Nullable<int> FROZENDATE { get; set; }
        public Nullable<int> FROZENTIME { get; set; }
        [MaxLength(40)]
        public string FROZENBY { get; set; }
        [MaxLength(100)]

        public string UNFROZENREASON { get; set; }
        public Nullable<int> UNFROZENDATE { get; set; }
        public Nullable<int> UNFROZENTIME { get; set; }
        [MaxLength(40)]

        public string UNFROZENBY { get; set; }
        [MaxLength(40)]

        public string MUSER { get; set; }
        public Nullable<int> MDATE { get; set; }
        public Nullable<int> MTIME { get; set; }
        [MaxLength(40)]

        public string EATTRIBUTE1 { get; set; }
    }
}
