//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table("TBLOQCLOT2CKGROUP")]
    public partial class OqcLot2CkGroup 
    {
        [MaxLength(40),Required]
        public string LOTNO { get; set; }
        [Required]
        public int LOTSEQ { get; set; }
        [MaxLength(40), Required]

        public string CKGROUP { get; set; }
        [Required]
        public int CHECKEDCOUNT { get; set; }
        [MaxLength(40), Required]

        public string MUSER { get; set; }
        [Required]
        public int MDATE { get; set; }
        [Required]
        public int MTIME { get; set; }
        [MaxLength(40)]

        public string EATTRIBUTE1 { get; set; }
        public Nullable<int> NEEDCHECKCOUNT { get; set; }
    }
}
