//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Models
{
    using Component.Tools;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    
    public enum TsStatus
    {
        NEW,
        CONFIRM
    }
    public partial class Ts:Entity
    {
      
        public Int64 TSID { get; set; }
        [MaxLength(40),Required]
        public string rcard { get; set; }
        [Required]
        public int rcardseq { get; set; }
        [MaxLength(40)]

        public string tcard { get; set; }
        [Required]
        public int tcardseq { get; set; }
        [MaxLength(40)]

        public string scard { get; set; }
        [Required]
        public int scardseq { get; set; }
        [MaxLength(40), Required]

        public string cardtype { get; set; }
        [MaxLength(40)]

        public string rrcard { get; set; }
        [MaxLength(40), Required]

        public string modelcode { get; set; }
        [MaxLength(40), Required]

        public string itemcode { get; set; }
        [MaxLength(40)]

        public string mocode { get; set; }
        [MaxLength(40)]

        public string frmroutecode { get; set; }
        [MaxLength(40)]

        public string frmopcode { get; set; }
        [MaxLength(40)]

        public string frmsegcode { get; set; }
        [MaxLength(40)]

        public string frmsscode { get; set; }
        [MaxLength(40)]

        public string frmrescode { get; set; }
        [MaxLength(40),Required]

        public string shifttypecode { get; set; }
        [MaxLength(40), Required]

        public string shiftcode { get; set; }
        [MaxLength(40), Required]

        public string tpcode { get; set; }
        [Required]
        public int shiftday { get; set; }
        [MaxLength(40), Required]

        public string frmuser { get; set; }
        [MaxLength(100)]

        public string frmmemo { get; set; }
        [Required]
        public int frmdate { get; set; }
        [Required]
        public int frmtime { get; set; }
        [MaxLength(40), Required]

        public string frminputtype { get; set; }
        [Required]
        public int tstimes { get; set; }
        [MaxLength(40),Required]
        public string tsstatus { get; set; }
        [MaxLength(40)]

        public string tsuser { get; set; }
        public Nullable<int> tsdate { get; set; }
        public Nullable<int> tstime { get; set; }
        [MaxLength(100)]

        public string tsmemo { get; set; }
        [MaxLength(40)]

        public string crescode { get; set; }
        [MaxLength(40)]

        public string copcode { get; set; }
        [MaxLength(40)]

        public string confirmuser { get; set; }
        public Nullable<int> confirmtime { get; set; }
        public Nullable<int> confirmdate { get; set; }
        [MaxLength(40)]

        public string refmocode { get; set; }
        [MaxLength(40)]

        public string refroutecode { get; set; }
        [MaxLength(40)]

        public string refopcode { get; set; }
        [MaxLength(40)]

        public string refrescode { get; set; }
        [MaxLength(40),Required]

        public string transstatus { get; set; }
        [MaxLength(100)]

        public string tffullpath { get; set; }
        [MaxLength(40),Required]

        public string muser { get; set; }
        [Required]
        public int mdate { get; set; }
        [Required]
        public int mtime { get; set; }
        [MaxLength(40)]

        public string eattribute1 { get; set; }
        [MaxLength(40)]

        public string tsrescode { get; set; }
        [MaxLength(200)]

        public string scrapcause { get; set; }
        public Nullable<int> frmmonth { get; set; }
        public Nullable<int> frmweek { get; set; }
        [MaxLength(40)]

        public string rmabillcode { get; set; }
        [MaxLength(40)]

        public string frmoutroutecode { get; set; }
        public Nullable<int> moseq { get; set; }
        [MaxLength(40)]

        public string tstype { get; set; }
        [MaxLength(40)]

        public string tsrepairuser { get; set; }
        public Nullable<int> tsrepairmdate { get; set; }
        public Nullable<int> tsrepairmtime { get; set; }

        public virtual ICollection<TsErrorCode> tsErrorCodes { get; set; }
    }
}
