//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Models
{
    using Component.Tools;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

  
    public partial class Ts:Entity
    {
      
        public Int64 TSID { get; set; }
        [MaxLength(40),Required]
        public string RCARD { get; set; }
        [Required]
        public int RCARDSEQ { get; set; }
        [MaxLength(40)]

        public string TCARD { get; set; }
        [Required]
        public int TCARDSEQ { get; set; }
        [MaxLength(40)]

        public string SCARD { get; set; }
        [Required]
        public int SCARDSEQ { get; set; }
        [MaxLength(40), Required]

        public string CARDTYPE { get; set; }
        [MaxLength(40)]

        public string RRCARD { get; set; }
        [MaxLength(40), Required]

        public string MODELCODE { get; set; }
        [MaxLength(40), Required]

        public string ITEMCODE { get; set; }
        [MaxLength(40)]

        public string MOCODE { get; set; }
        [MaxLength(40)]

        public string FRMROUTECODE { get; set; }
        [MaxLength(40)]

        public string FRMOPCODE { get; set; }
        [MaxLength(40)]

        public string FRMSEGCODE { get; set; }
        [MaxLength(40)]

        public string FRMSSCODE { get; set; }
        [MaxLength(40)]

        public string FRMRESCODE { get; set; }
        [MaxLength(40),Required]

        public string SHIFTTYPECODE { get; set; }
        [MaxLength(40), Required]

        public string SHIFTCODE { get; set; }
        [MaxLength(40), Required]

        public string TPCODE { get; set; }
        [Required]
        public int SHIFTDAY { get; set; }
        [MaxLength(40), Required]

        public string FRMUSER { get; set; }
        [MaxLength(100)]

        public string FRMMEMO { get; set; }
        [Required]
        public int FRMDATE { get; set; }
        [Required]
        public int FRMTIME { get; set; }
        [MaxLength(40), Required]

        public string FRMINPUTTYPE { get; set; }
        [Required]
        public int TSTIMES { get; set; }
        [MaxLength(40),Required]        
        public string TSSTATUS { get; set; }
        [MaxLength(40)]

        public string TSUSER { get; set; }
        public Nullable<int> TSDATE { get; set; }
        public Nullable<int> TSTIME { get; set; }
        [MaxLength(100)]

        public string TSMEMO { get; set; }
        [MaxLength(40)]

        public string CRESCODE { get; set; }
        [MaxLength(40)]

        public string COPCODE { get; set; }
        [MaxLength(40)]

        public string CONFIRMUSER { get; set; }
        public Nullable<int> CONFIRMTIME { get; set; }
        public Nullable<int> CONFIRMDATE { get; set; }
        [MaxLength(40)]

        public string REFMOCODE { get; set; }
        [MaxLength(40)]

        public string REFROUTECODE { get; set; }
        [MaxLength(40)]

        public string REFOPCODE { get; set; }
        [MaxLength(40)]

        public string REFRESCODE { get; set; }
        [MaxLength(40),Required]

        public string TRANSSTATUS { get; set; }
        [MaxLength(100)]

        public string TFFULLPATH { get; set; }
        [MaxLength(40),Required]

        public string MUSER { get; set; }
        [Required]
        public int MDATE { get; set; }
        [Required]
        public int MTIME { get; set; }
        [MaxLength(40)]

        public string EATTRIBUTE1 { get; set; }
        [MaxLength(40)]

        public string TSRESCODE { get; set; }
        [MaxLength(200)]

        public string SCRAPCAUSE { get; set; }
        public Nullable<int> FRMMONTH { get; set; }
        public Nullable<int> FRMWEEK { get; set; }
        [MaxLength(40)]

        public string RMABILLCODE { get; set; }
        [MaxLength(40)]

        public string FRMOUTROUTECODE { get; set; }
        public Nullable<int> MOSEQ { get; set; }
        [MaxLength(40)]

        public string TSTYPE { get; set; }
        [MaxLength(40)]

        public string TSREPAIRUSER { get; set; }
        public Nullable<int> TSREPAIRMDATE { get; set; }
        public Nullable<int> TSREPAIRMTIME { get; set; }
    }
}
