//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table("TBLTSERRORCAUSE")]
    public partial class TsErrorCause
    {
        [MaxLength(40),Required]
        public string ECODE { get; set; }
        [MaxLength(40), Required]

        public string ECSCODE { get; set; }
        [MaxLength(40), Required]

        public string ECGCODE { get; set; }
        [MaxLength(40), Required]

        public string TSID { get; set; }
        [MaxLength(40), Required]

        public string RCARD { get; set; }
        [Required]
        public int RCARDSEQ { get; set; }
        [MaxLength(40), Required]

        public string MODELCODE { get; set; }
        [MaxLength(40), Required]

        public string ITEMCODE { get; set; }
        [MaxLength(40)]
        public string MOCODE { get; set; }
        [MaxLength(40), Required]

        public string RRESCODE { get; set; }
        [MaxLength(40), Required]

        public string ROPCODE { get; set; }
        [MaxLength(40)]

        public string SOLCODE { get; set; }
        [MaxLength(40), Required]

        public string DUTYCODE { get; set; }
        [MaxLength(100)]

        public string SOLMEMO { get; set; }
        [MaxLength(40), Required]

        public string MUSER { get; set; }
        [Required]
        public int MDATE { get; set; }
        [Required]
        public int MTIME { get; set; }
        [MaxLength(40)]

        public string EATTRIBUTE1 { get; set; }
        public Nullable<int> SHIFTDAY { get; set; }
        [MaxLength(40), Required]

        public string ECSGCODE { get; set; }
        public Nullable<int> MOSEQ { get; set; }
    }
}
