//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table("TBLTSITEM")]
    public partial class  TsItem
    {
        [MaxLength(40),Required]
        public string TSID { get; set; }
        [Required]
        public int ITEMSEQ { get; set; }
        [MaxLength(40), Required]

        public string MODELCODE { get; set; }
        [MaxLength(40), Required]

        public string ITEMCODE { get; set; }
        [MaxLength(40)]

        public string MOCODE { get; set; }
        [MaxLength(40), Required]

        public string RCARD { get; set; }
        public Nullable<int> RCARDSEQ { get; set; }
        [MaxLength(40)]

        public string SITEMCODE { get; set; }
        [MaxLength(40)]

        public string MSCARD { get; set; }
        [Required]
        public int LOCPOINT { get; set; }
        [MaxLength(40)]

        public string LOC { get; set; }
        [MaxLength(40), Required]

        public string MITEMCODE { get; set; }
        [MaxLength(40)]

        public string MCARD { get; set; }
        [MaxLength(40), Required]

        public string MCARDTYPE { get; set; }
        [Required]
        public int QTY { get; set; }
        [MaxLength(40), Required]

        public string RRESCODE { get; set; }
        [MaxLength(40), Required]

        public string ROPCODE { get; set; }
        [MaxLength(40)]

        public string LOTNO { get; set; }
        [MaxLength(40), Required]

        public string ISRETS { get; set; }
        [MaxLength(40)]

        public string DATECODE { get; set; }
        [MaxLength(40)]

        public string PCBA { get; set; }
        [MaxLength(40)]

        public string BIOS { get; set; }
        [MaxLength(40)]

        public string REVERSION { get; set; }
        [MaxLength(40)]

        public string VENDORITEMCODE { get; set; }
        [MaxLength(40)]

        public string VENDORCODE { get; set; }
        [MaxLength(100)]

        public string MEMO { get; set; }
        [MaxLength(40),Required]

        public string MUSER { get; set; }
        [Required]
        public int MDATE { get; set; }
        [Required]
        public int MTIME { get; set; }
        [MaxLength(40)]

        public string EATTRIBUTE1 { get; set; }
        public Nullable<int> MOSEQ { get; set; }
    }
}
