//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

   
    public partial class Material
    {
        [Key,MaxLength(40)]
        public string MCODE { get; set; }
        [MaxLength(40)]
        public string MNAME { get; set; }
        [MaxLength(200)]
        public string MDESC { get; set; }
        [MaxLength(40)]
        public string MUOM { get; set; }
        [MaxLength(40),Required]
        public string MTYPE { get; set; }
        [MaxLength(40)]
        public string MMACHINETYPE { get; set; }
        [MaxLength(40)]
        public string MVOLUME { get; set; }
        [MaxLength(40)]
        public string MMODELCODE { get; set; }
        [MaxLength(40),Required]
        public string MEXPORTIMPORT { get; set; }
        [MaxLength(40)]
        public string MMODELGROUP { get; set; }
        [MaxLength(40)]
        public string MGROUP { get; set; }
        [MaxLength(40)]
        public string MGROUPDESC { get; set; }
        [MaxLength(40),Required]
        public string MCONTROLTYPE { get; set; }
        [MaxLength(40),Required]
        public string MUSER { get; set; }
        [Required]
        public int MDATE { get; set; }
        [Required]
        public int MTIME { get; set; }
        [MaxLength(40)]
        public string EATTRIBUTE1 { get; set; }
        
        [MaxLength(100)]
        public string MPARSETYPE { get; set; }
        [MaxLength(40)]
        public string CHECKSTATUS { get; set; }
        [MaxLength(40)]
        public string MCHECKTYPE { get; set; }
        public Nullable<int> SNLENGTH { get; set; }
        [MaxLength(40)]
        public string VENDORCODE { get; set; }
        [MaxLength(15)]
        public string ROHS { get; set; }
        [MaxLength(40)]
        public string NEEDVENDOR { get; set; }
        [MaxLength(40)]
        public string COMPONENTTYPE { get; set; }
        [MaxLength(40)]
        public string COMPONENTITEMCODE { get; set; }
        [MaxLength(200)]
        public string ENGLISHNAME { get; set; }
        [MaxLength(200)]
        public string CHINESENAME { get; set; }
        [MaxLength(200)]
        public string CKDMODEL { get; set; }
        [MaxLength(200)]
        public string EGYPTNAME { get; set; }
        [MaxLength(200)]
        public string PAKISTANNAME { get; set; }
        [MaxLength(200)]
        public string TAIWANNAME { get; set; }
        public virtual Org Org { get; set; }
    }
}
