//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

  
    public partial class Model
    {
        [Key,MaxLength(40)]
        public string MODELCODE { get; set; }
        [MaxLength(100)]
        public string MODELDESC { get; set; }
        [MaxLength(40),Required]
        public string MUSER { get; set; }
        [Required]
        public int MDATE { get; set; }
        [Required]
        public int MTIME { get; set; }
        [MaxLength(40)]
        public string EATTRIBUTE1 { get; set; }
        [MaxLength(1)]
        public string ISINV { get; set; }
        [MaxLength(1)]
        public string ISREFLOW { get; set; }
        [MaxLength(1)]
        public string ISCHECKDATALINK { get; set; }
        public Nullable<int> DATALINKQTY { get; set; }
        [MaxLength(1)]
        public string ISDIM { get; set; }
        public Nullable<int> DIMQTY { get; set; }
        
        public virtual ICollection<Item> Items { get; set; }
        public virtual Org Org { get; set; }
    }
}
