//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

   
    public partial class MoRcard
    {
        //[Key]
        public int MoRcardID { get; set; }
        [MaxLength(40),Required]
        public string MOCODE { get; set; }
        [Required]
        public int SEQ { get; set; }
        [MaxLength(40)]
        public string MORCARDSTART { get; set; }
        [MaxLength(30)]
        public string MORCARDEND { get; set; }
        [MaxLength(100)]
        public string MORCARDMEMO { get; set; }
        [MaxLength(40)]
        public string MUSER { get; set; }
        [Required]
        public int MTIME { get; set; }
        [Required]
        public int MDATE { get; set; }
        [MaxLength(40)]
        public string EATTRIBUTE1 { get; set; }
        public Nullable<int> MOSEQ { get; set; }
    }
}
