//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Models
{
    using Component.Tools;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

   
    public partial class MoRcard:Entity
    {
        //[Key]
        public int MoRcardID { get; set; }
        [MaxLength(40),Required]
        public string MoCode { get; set; }
        [Required]
        public int Seq { get; set; }
        [MaxLength(40)]
        public string MoCardStart { get; set; }
        [MaxLength(30)]
        public string MoCardEnd { get; set; }
        [MaxLength(100)]
        public string MoRcardMemo { get; set; }
        [MaxLength(40)]
        public string Muser { get; set; }
        [Required]
        public int Mtime { get; set; }
        [Required]
        public int Mdate { get; set; }
        [MaxLength(40)]
        public string eatTribute1 { get; set; }
        public Nullable<int> MoSeq { get; set; }
    }
}
